plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlinx-serialization'
}

android {
    namespace 'com.itsfrz.goonline'
    compileSdk 35
    buildToolsVersion "35.0.0"

    aaptOptions {
        cruncherEnabled = false
    }

    packaging {
        resources {
            excludes += ['META-INF/com/android/build/gradle/app-metadata.properties']
        }
    }

    defaultConfig {
        minSdk 23
        targetSdk 34
        vectorDrawables.generatedDensities = []

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    buildTypes {
        release {
            vcsInfo.include false
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }

    buildFeatures{
        compose false
        buildConfig true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.8"
    }

}

tasks.whenTaskAdded { task ->
    if (task.name.contains("ArtProfile")) {
        task.enabled = false
    }
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
    kotlinOptions {
        freeCompilerArgs += [
                "-P",
                "plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=true"
        ]
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:$app_compat_version"
    implementation "androidx.core:core-ktx:$core_ktx_version"
    testImplementation "junit:junit:$junit_test_version"
    androidTestImplementation "androidx.test.ext:junit:$junit_implementation_version"
    androidTestImplementation "androidx.test.espresso:espresso-core:$expresso_core_version"

//    // Datastore
    implementation "androidx.datastore:datastore-preferences:$datastore_version"
    implementation "org.jetbrains.kotlinx:kotlinx-collections-immutable:$kotlinx_collections_version"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:$serialization_json_version"
    implementation "com.squareup.retrofit2:converter-gson:$retrofit_json_converter_version"
}